version: '3'
services:
  web:
    image: nginx:latest
    ports:
      - "8090:80"    # Tu puerto HTTP actual
      - "8443:443"   # NUEVO: Puerto HTTPS
    volumes:
      
      - ./html:/usr/share/nginx/html 
      
      # NUEVO: Inyección del archivo de configuración
      - ./default.conf:/etc/nginx/conf.d/default.conf
      
      # NUEVO: Inyección de certificados
      - ./nginx-selfsigned.crt:/etc/ssl/certs/nginx-selfsigned.crt
      - ./nginx-selfsigned.key:/etc/ssl/private/nginx-selfsigned.key
    depends_on:
      - sftp-server

  sftp-server:
    image: atmoz/sftp
    ports:
      - "2223:22"
    volumes:
      - ./html:/home/user/upload   # <--- ¡Aquí están los dos puntos clave ":"!
    command: user:1234:1001        # <--- Tu usuario es 'user' y contraseña '1234'