version: '3'
services:
  web:
    image: nginx:latest
    ports:
      - "8090:80"    # puerto HTTP actual
      - "8443:443"   # Puerto HTTPS
    volumes:
      
      - ./webdata:/usr/share/nginx/html
      
      # Inyecci칩n del archivo de configuraci칩n
      - ./default.conf:/etc/nginx/conf.d/default.conf
      
      #Inyecci칩n de certificados
      - ./nginx-selfsigned.crt:/etc/ssl/certs/nginx-selfsigned.crt
      - ./nginx-selfsigned.key:/etc/ssl/private/nginx-selfsigned.key

      - ./.htpasswd:/etc/nginx/.htpasswd
    depends_on:
      - sftp-server

  sftp-server:
    image: atmoz/sftp
    ports:
      - "2223:22"
    volumes:
      - ./webdata:/home/user/upload   
    command: user:1234:1001        # usuario es 'user' y contrase침a '1234'